version: "3"  
services:
  app-node:
    image: book:2.0.0
    ports:
      - 3000:3000
    environment : 
      - HOSTDB=mongodb
      - PORTD=27017
    depends_on :
      - mongodb
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - 27018:27017
